### GET api status  
GET http://localhost:3000/

### POST - Register a user 
POST http://localhost:3000/auth/register 
Content-Type: application/json 

{
    "username": "sunboy6",
    "email": "test7@gmail.com",
    "password": "sunnyboy",
    "confirmPassword": "sunnyboy"
}

### POST - Register a user 2
POST http://localhost:3000/auth/register 
Content-Type: application/json 

{
    "username": "sunboy7",
    "email": "test8@gmail.com",
    "password": "sunnyboy",
    "confirmPassword": "sunnyboy"
}

### POST - Login a user 
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "identifier": "test7@gmail.com",
    "password": "sunnyboy"
}

### POST - Login a user 2
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "identifier": "sunboy7",
    "password": "sunnyboy"
}


### POST - Refresh a token
