### GET api status  
GET http://localhost:3000/

### POST - Register a user 
POST http://localhost:3000/auth/register 
Content-Type: application/json 

{
    "username": "sunboy6",
    "email": "test7@gmail.com",
    "password": "sunnyboy",
    "confirmPassword": "sunnyboy"
}